export const FETCH_WEBCAMS = 'FETCH_WEBCAMS';
export const FETCH_WEBCAMS_START = 'FETCH_WEBCAMS_START';
export const FETCH_WEBCAMS_SUCCESS = 'FETCH_WEBCAMS_SUCCESS';
export const FETCH_WEBCAMS_FAILED = 'FETCH_WEBCAMS_FAILED';
